import './globals.css'
import { Providers } from '@/app/providers'
import { CartProvider } from "./providers/CartProvider";
import { Toaster } from 'react-hot-toast';


export const metadata = {
  title: 'FOODNEXT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-maehongson text-gray-800 dark:bg-gray-900 dark:text-gray-100" suppressHydrationWarning>
        <Providers>
          <CartProvider>
            {children}
            <Toaster position="top-right" />
          </CartProvider>
        </Providers>
      </body>
    </html>
  )
}
